### NumPy 특징

- 과학 기술 계산을 위한 라이브러리 제공
- 백터/행렬/배열 처리 및 연산, 난수 발생
- 파일관리(txt, csv 등 파일 읽기/쓰기)
- 리스트(list) 형 데이터와 유사하지만 Numpy는 배열의 특징을 가짐
- 모든 원소는 동일한 자료형이어야 한다.
- 원소들 중 다른 자료형이 있다면 가장 큰 자료형으로 변경됨
- 계산 속도가 빠르다
- 벡터/연산, 배열 인덱싱 등을 통해 질의 가능

In [1]:
import numpy as np

In [10]:
lst = [1, 2, 3, 4, 5]
s = [i*2 for i in lst]

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [12]:
arr_lst = np.array(lst)
arr_lst*2

array([ 2,  4,  6,  8, 10])

#### numpy 연산
- 행렬 연산이라고 생각해라
     - 즉 데이터의 개수가 맞지 않으면 연산할 수 없다

In [14]:
#1차원 배열 구조, 즉 벡터 구조
arr1 = np.array([1,2,3])
arr2 = np.array([10, 20, 30])
print(arr1+arr2)
print(arr2>=20)

[11 22 33]
[False  True  True]


#### 넘파이를 두 벡터 연산시자료의 갯수는 동일해야 한다

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([10, 20, 30])

arr1 + arr2
#에러가 나온다 왜? 개수가 맞지 않으니까

#### 2차원 배열 구조

In [23]:
lst = [[0,0,1], [8, 12, 33]]
arr = np.array(lst)
print(lst)
print(arr)

[[0, 0, 1], [8, 12, 33]]
[[ 0  0  1]
 [ 8 12 33]]


In [24]:
print(len(lst))  # lst의 전체 데이터 개수
print(len(arr))  # arr의 행의 개수

print(len(lst[0])) # lst의 첫번째 데이터의 갯수
print(len(arr[0])) # arr의 열의 갯수

array([[ 0,  0,  1],
       [ 8, 12, 33]])

- numpy에서 움직이는 데이터는 갯수를 맞춰준다
- 그렇지 않으면 object를 받아와 버린다. 즉 list면 array([],[])

In [25]:
lst = [[0,0,1,1],[8, 12, 33]]
arr = np.array(lst)
arr

<ipython-input-25-0d602e3c051b>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array(lst)


array([list([0, 0, 1, 1]), list([8, 12, 33])], dtype=object)

#### 3차원 배열

In [32]:
lst = [[[10, 20, 30]]]
arr = np.array(lst)
print(arr.shape) # arr의 모양을 보는 방법 (차원)
#(면, 행, 열)
print(arr)

(1, 1, 3)
[[[10 20 30]]]


In [36]:
lst = [[[10, 20, 30],[15, 25, 35]]]
arr = np.array(lst)
print(arr.shape) # arr의 모양을 보는 방법 (차원)
#(면, 행, 열)
print(arr)

(1, 2, 3)
[[[10 20 30]
  [15 25 35]]]


- 배열을 만들려면 구조가 똑같아야한다

In [37]:
lst = [[[10, 20, 30], [15, 25, 35]],[[1.,2.,3.],[12, 13., 15]]]
arr = np.array(lst)
print(arr.shape) # arr의 모양을 보는 방법 (차원)
#(면, 행, 열)
print(arr)

(2, 2, 3)
[[[10. 20. 30.]
  [15. 25. 35.]]

 [[ 1.  2.  3.]
  [12. 13. 15.]]]


- 가장 큰 자료형으로 바꿔준다

In [38]:
lst = [[[10, 20, 30], [15, 25, 35]],[[1.,2.,3.],[12, 13., '15']]]
arr = np.array(lst)
print(arr.shape) # arr의 모양을 보는 방법 (차원)
#(면, 행, 열)
print(arr)

(2, 2, 3)
[[['10' '20' '30']
  ['15' '25' '35']]

 [['1.0' '2.0' '3.0']
  ['12' '13.0' '15']]]


####  파이썬 자료형
- NoneType / bool/ int / float / complex / str / tuple / list / dict/ fuction

In [39]:
from sys import getsizeof

a=1;b=1.;c='1'
print(getsizeof(a))
print(getsizeof(b))
print(getsizeof(c))

28
24
50


#### 배열 구조 데이터 인덱싱

In [40]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])

10


In [45]:
# 2차원 배열의 인덱싱

arr = np.array([[10, 20, 30, 40, 50],[15, 25, 35, 45, 55]])
print(arr[0])    # 첫번째 행 전체 출력해
print(arr[-1])   # 마지막 행 전체 출력해
print(arr[0][0]) #우리가 리스트에서 데이터 불러왔던 구조,
                 #0번째 행가져오고 0번쨰 열 데이터 가져와
print(arr[0, 0]) # 0번째 행 0번째 열 데이터 가져와

[10 20 30 40 50]
[15 25 35 45 55]
10
10


In [54]:
# 3차원 배열의 인덱싱

lst = [[[10, 20, 30], [15, 25, 35]],[[1.,2.,3.],[12, 13., 15]]]
arr = np.array(lst)
print(arr.shape)
print(arr)

(2, 2, 3)
[[[10. 20. 30.]
  [15. 25. 35.]]

 [[ 1.  2.  3.]
  [12. 13. 15.]]]


####  불리언(Boolean) 배열 방식을 이용한 인덱싱

In [64]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
atf = np.array([False, True, False, True, False, True, False, True,False, True])
print(arr[atf]) # Ture인 값만 매칭해서 출력
anum = np.array([0,2,4,6,8])
print(arr[anum]) # anum을 위치값으로 사용해 출력

[ 2  4  6  8 10]
[1 3 5 7 9]


In [67]:
print(arr[arr%2==1])
print(arr[arr%2==0])

[1 3 5 7 9]
[ 2  4  6  8 10]


In [69]:
arr = np.array([[10, 20, 30],[15, 25, 35],[1.,2.,3.],[12, 13., 15]])
arr

array([[10., 20., 30.],
       [15., 25., 35.],
       [ 1.,  2.,  3.],
       [12., 13., 15.]])

In [77]:
arr[[1,3], :] # 1행이랑 3행 가져오고 열은 다가져와

array([[15., 25., 35.],
       [12., 13., 15.]])

#### 배열 생성/구조 변경

In [78]:
arr = np.array([15, 25, 35 ,45])
arr.dtype

dtype('int32')

In [84]:
arr = np.array([15, 25, 35 ,45], dtype = 'd')
arr.dtype

dtype('float64')

In [88]:
arr[1] = 28
arr

array([15., 28., 35., 45.])

In [92]:
arr = np.arange(1, 10 ,2)
arr

array([2, 4, 6, 8])

In [98]:
arr = np.arange(10,1, -1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [111]:
arr = np.logspace(0,1, 10) #10^0승부터 10^1승까지 10개 구간으로 나눈다
# np.logspace(a,b, c) 10^a부터 10^b 승까지 c 개의 구간으로 나눠라
arr

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [114]:
arr = np.linspace(0, 100, 5, endpoint = False) # 0 부터 100까지 실수범위 5구간으로 나눠라 마지막 값은 제거한다
arr

array([ 0., 20., 40., 60., 80.])

#### 배열 데이터 변경

In [116]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr_res = arr.reshape(5, 2)
arr_res


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [136]:
arr = np.ones(50) # 50개의 데이터를 다 0로
len(arr)
arr = np.zeros(50) # 50개의 데이터를 다 0 으로
arr_res = arr.reshape(10, -1)
# 행또는 열 위치에 -1를 넣으면 자동 생성
# 다만 arr.reshape(-1,-1)은 에러
arr_res

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [146]:
arr_res.reshape(-1,5,2) # 3차원 구조로도 변경가능
# 즉 차원도 마음데로 바꿀수 있음

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [147]:
arr_res.reshape(-1) # 즉 1차원으로도 다시변경 가능

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [159]:
arr = np.arange(1, 61)
arr_res = arr.reshape(-1, 6)
arr_res

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [167]:
arr_res[0] = 0
arr_res

array([[ 0,  0,  0,  0,  0,  0],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  1,  1,  1,  1,  1],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [168]:
arr_res[0,2] = 10
arr_res

array([[ 0,  0, 10,  0,  0,  0],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  1,  1,  1,  1,  1],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

####  브로드캐스팅(broad casting) & 마스킹(masking)
 - 하나의 배열 or 요소가 어떤 특정 배열에 영향을 미칠때 배열간의 형상을 맞추는 것을 브로드 캐스팅이라고함

In [169]:
#arr_res 배열에서 값을 나누고 남은 나머지가 0이면 True 반환
#idx 변수를 만들어(=masking을 만듬) True/False로 변환된 데이터 저장
idx = arr_res%2==0
idx

array([[ True,  True,  True,  True,  True,  True],
       [False,  True, False,  True, False,  True],
       [False, False, False, False, False, False],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True]])

In [171]:
# 만들어진 idx의 마스킹 값을 기준으로 True인 값만 출력
arr_res[idx] = 100
arr_res
#True 값만 뽑아서 100으로 바꿔라

array([[100, 100, 100, 100, 100, 100],
       [  7, 100,   9, 100,  11, 100],
       [  1,   1,   1,   1,   1,   1],
       [ 19, 100,  21, 100,  23, 100],
       [ 25, 100,  27, 100,  29, 100],
       [ 31, 100,  33, 100,  35, 100],
       [ 37, 100,  39, 100,  41, 100],
       [ 43, 100,  45, 100,  47, 100],
       [ 49, 100,  51, 100,  53, 100],
       [ 55, 100,  57, 100,  59, 100]])

#### NumPy에서 파일 읽고/쓰기